import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
    initDependencies: () => ipcRenderer.invoke('init-dependencies'),
    selectFolder: (title?: string) => ipcRenderer.invoke('select-folder', title),
    searchYoutube: (query: any) => ipcRenderer.invoke('search-youtube', query),
    fetchMetadata: (url: string) => ipcRenderer.invoke('fetch-metadata', url),
    downloadSong: (data: any) => ipcRenderer.invoke('download-song', data),
    scanLibrary: (folder: string) => ipcRenderer.invoke('scan-library', folder),
    spotifyLogin: () => ipcRenderer.invoke('spotify-login'),
    spotifyGetToken: () => ipcRenderer.invoke('spotify-get-token'),
    spotifyLogout: () => ipcRenderer.invoke('spotify-logout'),
    spotifyGetConfig: () => ipcRenderer.invoke('spotify-get-config'),
    spotifySetClientId: (clientId: string | null) => ipcRenderer.invoke('spotify-set-client-id', clientId),
    djDetectLibraries: () => ipcRenderer.invoke('dj-detect-libraries'),
    djOwnedTracks: () => ipcRenderer.invoke('dj-owned-tracks'),
    djLoadLibraries: (req: any) => ipcRenderer.invoke('dj-load-libraries', req),
    djSelectXml: (kind: 'rekordbox' | 'itunes') => ipcRenderer.invoke('dj-select-xml', kind),
    djOpenRekordbox: () => ipcRenderer.invoke('dj-open-rekordbox'),
    djGetDestinations: () => ipcRenderer.invoke('dj-get-destinations'),
    djSetDestinations: (destinations: any[]) => ipcRenderer.invoke('dj-set-destinations', destinations),
    djScanFolder: (folder: string) => ipcRenderer.invoke('dj-scan-folder', folder),
    djApplyTriage: (assignments: any[]) => ipcRenderer.invoke('dj-apply-triage', assignments),
    djRevealFile: (filePath: string) => ipcRenderer.invoke('dj-reveal-file', filePath),
    djGetArtwork: (filePath: string) => ipcRenderer.invoke('dj-get-artwork', filePath),
});
