from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import requests
import os
import base64
import re
import time

app = FastAPI()

# Allow CORS so your React app can talk to this server from anywhere (localhost or production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, change this to your app's domain if possible
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load environment variables
CLIENT_ID = os.environ.get("SPOTIFY_CLIENT_ID")
CLIENT_SECRET = os.environ.get("SPOTIFY_CLIENT_SECRET")

# Simple in-memory cache to avoid hitting Spotify too often
# Structure: {'token': '...', 'expires_at': 1234567890}
token_cache = {}

@app.get("/")
def home():
    return {"status": "ok", "service": "Spotify Token Proxy"}

@app.get("/token")
def get_spotify_token():
    global token_cache
    
    if not CLIENT_ID or not CLIENT_SECRET:
        raise HTTPException(status_code=500, detail="Server misconfigured: Missing Spotify credentials")

    # Check valid cache
    if token_cache and token_cache.get('expires_at', 0) > time.time():
        return token_cache['payload']

    # Request new token
    auth_url = 'https://accounts.spotify.com/api/token'
    
    # Spotify requires Base64 encoded ID:Secret
    auth_str = f"{CLIENT_ID}:{CLIENT_SECRET}"
    b64_auth = base64.b64encode(auth_str.encode()).decode()

    headers = {
        'Authorization': f'Basic {b64_auth}',
        'Content-Type': 'application/x-www-form-urlencoded'
    }
    
    data = {'grant_type': 'client_credentials'}

    try:
        response = requests.post(auth_url, headers=headers, data=data)
        response.raise_for_status()
        
        json_data = response.json()
        
        # Cache the result (expires_in is usually 3600 seconds)
        # We subtract 60s buffer to be safe
        expires_in = json_data.get('expires_in', 3600)
        token_cache = {
            'payload': json_data,
            'expires_at': time.time() + expires_in - 60
        }
        
        return json_data
        
    except requests.exceptions.RequestException as e:
        print(f"Error fetching token: {e}")
        raise HTTPException(status_code=502, detail="Failed to communicate with Spotify")

@app.get("/client-id")
def get_client_id():
    """
    Returns the PUBLIC Spotify client ID so the desktop app can run the
    Authorization Code + PKCE flow (user login). The client secret is
    never exposed - PKCE does not need it.
    """
    if not CLIENT_ID:
        raise HTTPException(status_code=500, detail="Server misconfigured: Missing Spotify client ID")
    return {"client_id": CLIENT_ID}

@app.get("/config")
def get_config():
    """
    Returns dynamic configuration for the frontend (messages, toasts).
    Controlled via Environment Variables on Render.
    """
    return {
        "release": {
            "text": os.environ.get("RELEASE_TEXT"),
            "link": os.environ.get("RELEASE_LINK")
        },
        "toast": {
            "text": os.environ.get("TOAST_TEXT"),
            "link": os.environ.get("TOAST_LINK")
        }
    }


# ---------------------------------------------------------------------------
# ANONYMOUS USAGE ANALYTICS
#
# Privacy rules (intentional, do not "improve"):
#   - No IP addresses, no account info, no track/playlist names. Ever.
#   - install_id is a random UUID generated by the app on first launch;
#     it identifies an INSTALL, not a person.
#   - Only whitelisted event names with a bare counter are accepted.
#
# Storage: external Postgres (e.g. free Neon instance) because Render's
# free-tier filesystem is wiped on every restart. Set DATABASE_URL in the
# Render dashboard. Without it, /event responds 200 and drops the data so
# clients never see errors.
# ---------------------------------------------------------------------------

DATABASE_URL = os.environ.get("DATABASE_URL")
STATS_KEY = os.environ.get("STATS_KEY")  # secret for reading /stats

ALLOWED_EVENTS = {"app_launch", "download"}
UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")

_db_ready = False


def _db_conn():
    """One connection per request — traffic is tiny and Neon idle-suspends."""
    import psycopg
    global _db_ready
    conn = psycopg.connect(DATABASE_URL, connect_timeout=10)
    if not _db_ready:
        # NB: not `with conn:` — psycopg3 closes the connection on block exit
        with conn.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS events (
                    id          BIGSERIAL PRIMARY KEY,
                    install_id  UUID NOT NULL,
                    app_version TEXT NOT NULL,
                    arch        TEXT NOT NULL,
                    event       TEXT NOT NULL,
                    count       INTEGER NOT NULL DEFAULT 1,
                    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                CREATE INDEX IF NOT EXISTS idx_events_created ON events (created_at);
                CREATE INDEX IF NOT EXISTS idx_events_install ON events (install_id);
            """)
        conn.commit()
        _db_ready = True
    return conn


class AnalyticsEvent(BaseModel):
    install_id: str
    app_version: str = Field(max_length=32)
    arch: str = Field(max_length=16)
    event: str
    count: int = Field(default=1, ge=1, le=10000)


@app.post("/event")
def post_event(ev: AnalyticsEvent):
    # Validate strictly; reject anything that isn't a plain anonymous counter
    if ev.event not in ALLOWED_EVENTS:
        raise HTTPException(status_code=400, detail="Unknown event")
    if not UUID_RE.match(ev.install_id.lower()):
        raise HTTPException(status_code=400, detail="Invalid install_id")

    if not DATABASE_URL:
        return {"ok": True}  # no DB configured: accept & drop, never break clients

    try:
        with _db_conn() as conn, conn.cursor() as cur:
            cur.execute(
                "INSERT INTO events (install_id, app_version, arch, event, count) VALUES (%s, %s, %s, %s, %s)",
                (ev.install_id.lower(), ev.app_version, ev.arch, ev.event, ev.count),
            )
        return {"ok": True}
    except Exception as e:
        print(f"[Analytics] insert failed: {e}")
        return {"ok": False}  # still 200 — clients must never care


@app.get("/stats")
def get_stats(key: str = ""):
    """Usage summary. Protected by STATS_KEY (set it in the Render dashboard)."""
    if not STATS_KEY or key != STATS_KEY:
        raise HTTPException(status_code=403, detail="Forbidden")
    if not DATABASE_URL:
        raise HTTPException(status_code=503, detail="No DATABASE_URL configured")

    try:
        with _db_conn() as conn, conn.cursor() as cur:
            def one(sql):
                cur.execute(sql)
                return cur.fetchone()[0]

            def rows(sql):
                cur.execute(sql)
                return cur.fetchall()

            return {
                "installs": {
                    "total": one("SELECT COUNT(DISTINCT install_id) FROM events"),
                    "active_30d": one("SELECT COUNT(DISTINCT install_id) FROM events WHERE created_at > now() - interval '30 days'"),
                    "active_7d": one("SELECT COUNT(DISTINCT install_id) FROM events WHERE created_at > now() - interval '7 days'"),
                },
                "downloads": {
                    "total": one("SELECT COALESCE(SUM(count), 0) FROM events WHERE event = 'download'"),
                    "last_7d": one("SELECT COALESCE(SUM(count), 0) FROM events WHERE event = 'download' AND created_at > now() - interval '7 days'"),
                    "last_30d": one("SELECT COALESCE(SUM(count), 0) FROM events WHERE event = 'download' AND created_at > now() - interval '30 days'"),
                },
                "launches_7d": one("SELECT COALESCE(SUM(count), 0) FROM events WHERE event = 'app_launch' AND created_at > now() - interval '7 days'"),
                # Latest version/arch reported by each install active in the last 30 days
                "by_version": dict(rows("""
                    SELECT app_version, COUNT(*) FROM (
                        SELECT DISTINCT ON (install_id) install_id, app_version
                        FROM events WHERE created_at > now() - interval '30 days'
                        ORDER BY install_id, created_at DESC
                    ) t GROUP BY app_version ORDER BY 2 DESC
                """)),
                "by_arch": dict(rows("""
                    SELECT arch, COUNT(*) FROM (
                        SELECT DISTINCT ON (install_id) install_id, arch
                        FROM events WHERE created_at > now() - interval '30 days'
                        ORDER BY install_id, created_at DESC
                    ) t GROUP BY arch ORDER BY 2 DESC
                """)),
            }
    except Exception as e:
        print(f"[Analytics] stats failed: {e}")
        raise HTTPException(status_code=500, detail="Stats query failed")

